<html>
<HEAD>
<?PHP
include('scripts/executetime.php');
?>
<title>Starshatter Dev. - the place to find stuff you won't find anywhere else.</title>
<meta http-equiv="Content-Type" content="text/HTML; charset=iso-8859-1">
<meta name="author" content="Pheagey Grean">
<meta name="keywords" content="Starshatter, MODs, MOD, def files, meshs, 3D meshs, SS">
<meta name="description" content="A leading sourch for Stashatter MOD info.">
<meta name="reply-to" content="p_grean@hotmail.com">
<meta http-equiv="expires" content="30">

<STYLE>
IMG {behavior:url("scripts/pngbehavior.htc");}
</STYLE>
<LINK title="main" href="css/main.css" type="text/css" rel="stylesheet">
<LINK title="windef" href="css/windef.css" type="text/css" rel="alternate stylesheet">
<LINK title="aqublu" href="css/aqublu.css" type="text/css" rel="alternate stylesheet">
<!--used to change css's-->
<SCRIPT src="scripts/styleswitcher.js" type="text/javascript"></SCRIPT>
<SCRIPT language="JavaScript">
icon_image = new Image();
icon_image.src="ssd.ico";
</SCRIPT>
<LINK REL="SHORTCUT ICON" HREF="ssd.ico" >
<SCRIPT LANGUAGE=javascript src="scripts/lines.js"></SCRIPT>
</HEAD>
<body onResize="resizeBars();" onLoad="resizeBars(); setEvents(); checkOpera();"  bottommargin="0" marginheight="0" marginwidth="0" rightmargin="0" scroll="yes" topmargin="0" leftmargin="0">
<!--used to show the menu-->
<SCRIPT language=JavaScript src="scripts/menu_array.js"type="text/javascript"></SCRIPT>

<script src="scripts/titlelines.js"></script>
<script src="scripts/menu.js"></script>
<div class="bodytable">



<table width="775" align="center" cellpadding="7" cellspacing="7" border="0" bordercolor="#0000ff" >

<tr><td class="sixsix" colspan="2"><font class="newtitle">SSD Communications center. Links, Forums and whatever...</font></td>

<td rowspan="99" width="100" class="fourfour" height="100%" valign="top">
<script src="scripts/rightsidemenu.js"></script>
</td>
</tr>

<tr>
<td class="fourfour" rowspan="7" width="15%" align="left" valign="top"><font class="words1">
<font class="lgshipdesigners">Quick links:</font><br><br>
&nbsp;&nbsp;&nbsp;<a href="#comm-links" class="shipdesigners">Link</a><br>
&nbsp;&nbsp;&nbsp;<a href="#comm-forums" class="shipdesigners">Forums</a><br>
&nbsp;&nbsp;&nbsp;<a href="#comm-email" class="shipdesigners">eMail</a><br>
</font>
</td>

<td class="fourfour" align="left" valign="top">
<a name="comm-links"></a>
<p align="left"><font class="newtitle">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Links:</font></p>
<a href="Http://www.Starshatter.com" target="_new" class="links">The officeal Starshatter Site.</a>
<font class="words1">&#160;&#160;&#160Till the reason for this site.</font><br><br>

<a href="Http://www.angelfire.lycos.com/scifi2/ssd" target="_new" class="links">Starshatter Dev.</a>
<font class="words1">&#160;&#160;&#160This palce, nice, clean, informative. run by ew ( Pheagey ), avaliable for all.</font><br><br>


<a href="Http://ssd.servehttp.com/cess/" target="_new" class="links">Crazy-Eddie's starshatter site.</a>
<font class="words1">&#160;&#160;&#160Nice little beginners site.</font><br><br>

</td>
</tr>

<tr>
<td class="fourfour" align="left" valign="top">
<a name="comm-forums"></a>
<p align="left"><font class="newtitle">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Forums:</font></p>
<a name="generalforum"></a>
<a href="forums/genforum/main.php" target="_self" class="links">SSD General Forum</a>
<font class="words1">&#160;&#160;&#160Basic stuff about Starshatter or SSD.</font><br><br>
<a name="techforum"></a>
<a href="forums/techforum/main.php" target="_self" class="links">SSD Tech Forum</a>
<font class="words1">&#160;&#160;&#160Technical stuff. Discussions on graphics engines, poly manipulation, reflectivity, MAGIC, Starshatter systems, etc/</font><br><br>

<a name="gfxforum"></a>
<a href="forums/gfxforum/main.php" target="_self" class="links">SSD Graphics Forum</a>
<font class="words1">&#160;&#160;&#160Graphics forum. Questions and discussion on textureing, graphics manipulations, screenshot postings, etc.</font><br><br>

<a name="gfxforum"></a>
<a href="forums/sctossforum/main.php" target="_self" class="links">Starcraft MOD Forum</a>
<font class="words1">&#160;&#160;&#160Starcraft MOD forum. Anything related to the Starcraft to Starshatter convertion.</font><br><br>
</td></tr>

<tr>
<td class="fourfour" align="left" valign="top">
<a name="comm-email"></a>
<p align="left"><font class="newtitle">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;eMails:</font></p>
<a href="mailto:pheageygrean@hotmail.com" target="_new" class="links">SSD Admin.</a>
<font class="words1">&#160;&#160;&#160The person that runs this here site.</font><br><br>
<a href="mailto:pheageygrean@hotmail.com" target="_new" class="links">Pheagey (member)</a>
<font class="words1">&#160;&#160;&#160I run this place; code it, graphics, forum, everything. I also play Starshatter (mm dua), do some Magic modeling, and stuff...</font><br><br>



</td>
</tr>
<tr><td class="sixsix" align="center" valign="bottom">
<font>
<?PHP include('scripts/executetime2.php');?>
</font>
</td></tr>
</table>
<script src="scripts/contact-copyright.js"></script>
</div>
</body>
</html>

