<html>
<HEAD>
<?PHP
include('scripts/executetime.php');
?>
<title>Starshatter Dev. - the place to find stuff you won't find anywhere else.</title>
<meta http-equiv="Content-Type" content="text/HTML; charset=iso-8859-1">
<meta name="author" content="Pheagey Grean">
<meta name="keywords" content="Starshatter, MODs, MOD, def files, meshs, 3D meshs, SS">
<meta name="description" content="A leading sourch for Stashatter MOD info.">
<meta name="reply-to" content="p_grean@hotmail.com">
<meta http-equiv="expires" content="30">

<STYLE>
IMG {behavior:url("scripts/pngbehavior.htc");}
</STYLE>
<LINK title="main" href="css/main.css" type="text/css" rel="stylesheet">
<LINK title="windef" href="css/windef.css" type="text/css" rel="alternate stylesheet">
<LINK title="aqublu" href="css/aqublu.css" type="text/css" rel="alternate stylesheet">
<!--used to change css's-->
<SCRIPT src="scripts/styleswitcher.js" type="text/javascript"></SCRIPT>
<SCRIPT language="JavaScript">
icon_image = new Image();
icon_image.src="ssd.ico";
</SCRIPT>
<LINK REL="SHORTCUT ICON" HREF="ssd.ico" >
<SCRIPT LANGUAGE=javascript src="scripts/lines.js"></SCRIPT>
</HEAD>
<body onResize="resizeBars();" onLoad="resizeBars(); setEvents(); checkOpera();"  bottommargin="0" marginheight="0" marginwidth="0" rightmargin="0" scroll="yes" topmargin="0" leftmargin="0">
<!--used to show the menu-->
<SCRIPT language=JavaScript src="scripts/menu_array.js"type="text/javascript"></SCRIPT>

<script src="scripts/titlelines.js"></script>
<script src="scripts/menu.js"></script>
<div class="bodytable">



<table width="775" align="center" cellpadding="7" cellspacing="7" border="0" bordercolor="#0000ff" >

<tr><td class="sixsix" colspan="2"><font class="newtitle">Offical Starshatter files for download.</font></td>

<td rowspan="99" width="100" class="fourfour" height="100%" valign="top">
<script src="scripts/rightsidemenu.js"></script>
</td>
</tr>

<tr>
<a name="SS"></a>
<td class="fourfour" rowspan="7" width="15%" align="left1" valign="top">
<font class="words1">
<font class="lgshipdesigners">Quick links:</font><br><br>
<a href="#files-offical-ss3-5" class="shipdesigners">Starshatter 3.5</a><br><br>
<a href="#files-offical-ss3-7-6" class="shipdesigners">Starshatter 3.7.6 Patch</a><br><br>
<a href="#files-offical-legacyss" class="shipdesigners">Legacy version of Starshatter</a><br><br>
<a href="#files-offical-DATmaker" class="shipdesigners">.DAT file maker</a><br><br>
<a href="#files-offical-magic1" class="shipdesigners">Magic 1</a><br><br>
<a href="#files-offical-magic1-4" class="shipdesigners">Magic 1.4</a><br><br>

</font>
</td>

<td class="fourfour" align="left" valign="top">
<a name="files-offical-ss3-5"></a>
<font class="newtitle">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Starshatter</font><br><br>
<font class="words2">
<a href="officalfiles/stars35.zip" class="links">Starshatter 3.5 Demo (34Megs)</a>
<font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.5 Starshatter Demo.</font><br><br>
<ul type="disc"><font class="words3">Features:</font>
	<li>more than 5 fast action missions,</li>
	<li>2 improved mini campagins,</li>
	<li>New ships and fighters added:
		<ul>
		<li>Terellian Alliance Light Cruiser "Courageous" class</li>
		<li>Marakan Hegemony Destroyer "Broadsword" class</li>
		<li>Marakan Hegemony Frigate "Baikal" class (also used by R.A. forces)</li>
		<li>And there is a new Hegemony fighter called the F-MK2 "Razor"</li>
		</ul>
	</li>
	<li>improved graphics and interface,</li>
	<li>much more!</li>
</ul>
<br><br><br>

<a name="files-offical-ss3-7-6"></a>
<a href="officalfiles/stars376.zip" class="links">Starshatter 3.7.6 patch (1,115K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.7.6 Starshatter patch.</font><br><br>
<ul type="disc"><font class="words2">Fix's:</font>
<li>Fixed crash when using auto skip with an escorting vessel</li>
<li>Fixed intermittent GUI crash</li>
<li>Fixed Farcaster support in  mission editor</li>
<li>Fixed disappearing weapon screen in mod fighters</li>
<li>Mission region now defaults to player region in mission editor</li>
<li>AI pilots should now obey orders more consistently when under fire</li>
</ul>
<br><br><br>

<a href="officalfiles/stars375.zip" class="links">Starshatter 3.7.5 patch (1,115K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.7.5 Starshatter patch.</font><br><br>
<ul type="disc"><font class="words2">Fix's:</font>
<li>Beam weapons now do correct damage against shielded targets</li>
<li>Beam weapons can now hit and destroy drones</li>
<li>Turret weapons on fighters correctly default to defensive fire mode (the primary gun always defaults to player control)</li>
<li>Own ship is now only selectable in F3 orbit cam</li>
<li>Missile ETA display no longer capped at 4 minutes</li>
<li>HUD now displays long ranges using "M" for millions of meters</li>
<li>Navlights, drive flares, and some weapons effects are now visible at ranges up to 1,000 km</li>
<li>Improved support for lead pursuit missiles</li>
<li>Improved AI tactical decision making (and feedback)</li>
<li>Approximate range data now returned for passive contacts</li>
<li>Double-click on HUD elements no longer sets starship helm order</li>

<li>
<ul type="square">NEW FEATURES IN 3.7.5
<li>MOD Configurator</li>
<li>Mission Editor</li>
<li>Player Logbook</li>
<li>Exec Command </li>
<li>AI Difficulty Levels </li>
</ul>
</li>

<li>
<ul type="square">NEW MOD TOOLS
<li>Animated weapon sprites</li>
<li>Articulated (two-piece) weapon turrets</li>
<li>Integrity value for drone weapons</li>
<li>Missile eject vector</li>
<li>WC-style capacitor based shields</li>
<li>New starship classes: Corvette, Battleship, Dreadnaught</li>
<li>Ship design setting to control starship banked turns</li>
<li>Ship design params to enable weapons and repair screens in all ship classes</li>
</ul></li>
</ul></li>
<br><br><br>

<a href="officalfiles/stars356.zip" class="links">Starshatter 3.5.6 patch (769K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.5.6 Starshatter patch.</font><br><br>
<ul type="disc"><font class="words2">Fix's:</font>

<li>New weapon design param:
<ul type="square"><li>light_color - sets the color of the light emitted by the shot</li></ul>
</li>
<li>New ship design params:
<ul type="square">
<li>repair_speed - scale factor for repair times. 2 means twice as fast as normal. Default is 1.</li>
<li>repair_teams - number of systems that can be repaired at one time. Default is 2.</li>
<li>repair_auto - boolean to enable auto repair feature. Default is true for starships, false for fighters.</li>
<li>repair_screen - boolean to enable use of ENG dialog. Default is true for starships, false for fighters</li>
</ul>
</li>
</ul>
<br><br><br>

<a href="officalfiles/stars355.zip" class="links">Starshatter 3.5.5 patch (750K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.5.5 Starshatter patch.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
<li>Fixes the auto/beam bug, and slightly nerfs torpedo damage bleed through to something closer to what it was in 3.5.3,</li>

</ul>
<br><br><br>

<a href="officalfiles/stars354.zip" class="links">Starshatter 3.5.4 patch (750K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.5.4 Starshatter patch.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
<li>Support for 3rd party sound effects created in Sound Recorder,</li>
<li>Support for large textures - the game engine will scale them down for older video cards,</li>
<li>Better "escort" AI,</li>
<li>Smooth turret movement,</li>
<li>Smart weapons fire for starships,</li>
<li>Beam weapons with multiple muzzle points,</li>
<li>Submunition weapon types,</li>
<li>Fix for the zero damage bug,</li>
<li>Power drain and EMP damage types for custom weapons,</li>
<li>Better self-defense AI for starships,</li>
<li>AI support for shielded fighters,</li>
<li>Improved fighter AI for using Farcasters,</li>
<li>EVE-style helm setting using mouse double-click,</li>
<li>I'm sure there's one or two more I'm forgetting, but you get the general idea</li>
</ul>
<br><br><br>

<a href="officalfiles/stars353.zip" class="links">Starshatter 3.5.3 patch (739K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.5.3 Starshatter patch.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
	<li>fixes a couple of really obscure crash bugs ,</li>
	<li>corrects the initial settings for the joystick pitch axis and throttle axis,</li>
	<li>help reduce the amount of wingman collisions,</li>
	<li>reduce the problem with sweep and shuttle escort missions not having any targets in the dynamic campaign. Sweep missions will still come up empty sometimes because there just aren't that many bad guys to hunt down in this version of the campaign. You can always check to see if you will have any opposition before you launch the mission. Go to the PKG tab in the mission briefing and see if any threats are listed on the right hand side. If there aren't any listed, there won't be any in the sim and you can cancel the mission and pick a different one.
</li>
</ul>
<br><br><br>

<a href="officalfiles/stars352.zip" class="links">Starshatter 3.5.2 patch (738K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.5.2 Starshatter patch.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
	<li>fixes a couple of joystick/performance problems,</li>
	<li>adds support for steering/throttle control using joystick buttons or hats,</li>
	<li>provides better support for running on low-memory video cards,</li>
	<li>fixes the crash bug found when leaving out a spin vector,</li>
	<li>fixes the stand down crash bug,</li>
	<li>provides support for 64 textures per model.</li>
</ul>
<br><br><br>

<a href="officalfiles/stars351.zip" class="links">Starshatter 3.5.1 patch (737K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.5.1 Starshatter patch.<br><br>

<br><br><br>
</td>
</tr>

<tr>
<td class="fourfour" align="left" valign="top">
<a name="files-offical-legacyss"></a>
<font class="newtitle">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Legacy versions of Starshatter</font><br><br>
<a href="officalfiles/stars30.zip" class="links">Starshatter 3.0.1 Demo (34Megs)</a>
<font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.0.1 Starshatter Demo.<br><br>
<ul type="disc"><font class="words3">Features:</font>
	<li>5 fast action missions,</li>
	<li>2 mini campagins,</li>
	<li>introduces the Asher class into the SS universe,</li>
	<li>improved graphics and interface,</li>
	<li>1st version to include easy mission MOD-ing.</li>
	<li>much more!</li>
</ul>
<br><br><br>
<a href="officalfiles/stars304.zip" class="links">Starshatter 3.0.4 patch (700K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.0.4 Starshatter patch.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
	<li>Balacned PDB's- there no longer death weapons as before. Much less powerful / range.,</li>
	<li>sheild protect / power usage tweaked</li>
</ul>
<br><br><br>
<a href="officalfiles/stars303.zip" class="links">Starshatter 3.0.3 patch (701K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 3.0.3 Starshatter patch.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
	<li>down graded 512*512 textures for GFX cards that cna not handle textures over 256*256 (some Voodoo3's, etc.),</li>
</ul>
<br><br><br>
<a href="officalfiles/stars20.zip" class="links">Starshatter 2.0 Demo (11140K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 2.0 Starshatter demo.
<br><br><br>
<a href="officalfiles/stars10.zip" class="links">Starshatter 1.0 Demo (6550K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical 1.0 Starshatter demo.
</font>
</td>
</tr>

<tr>
<td class="fourfour" align="left" valign="top">
<a name="files-offical-DATmaker"></a>
<font class="newtitle">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.DAT Maker</font><br><br>
<font class="words2">
<a href="officalfiles/datfilemaker.zip" class="links">.DAT file maker (64.5K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The offical .DAT file maker.</font><br><br>
<ul type="disc"><font class="words2">Use:
<li>Create non decompilable .DAT files.
<ul type="square"><li>Readme / Instruction included.</li></ul>
</li>
</ul>
<br><br><br>
</font>
</td>
</tr>

<tr>
<td class="fourfour" align="left" valign="top">
<a name="files-offical-magic1-4"></a>
<font class="newtitle">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Magic</font><br><br>
<font class="words2">
<a href="officalfiles/Magic1-3.zip" class="links">Magic 1.4  update (275K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Update patch for the Magic 3D program.<br><br>
<ul type="disc"><font class="words2">Addition's:</font>
	<li>Added *.3DS file import ability.</li>
	<li>Fixed the dropping exactly 1 poly when importing OBJ files.
</ul>
<br><br><br>

<a href="officalfiles/Magic1-3.zip" class="links">Magic 1.3 update (251K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Update patch for the Magic 3D program.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
	<li>some issues with the OBJ importing and textures.</li>
</ul>
<br><br><br>

<a href="officalfiles/Magic1-2.zip" class="links">Magic 1.2 update (251K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Update patch for the Magic 3D program.<br><br>
<br><br><br>

<a name="files-offical-magic1"></a>
<a href="officalfiles/Magic1-1.zip" class="links">Magic 1.1 full (540K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Updated version of the Magic 3D program.<br><br>
<ul type="disc"><font class="words2">Fix's:</font>
	<li>Added the ability to import .OBJ files. Doesn't retain texture or UV info but hell, it works.</li>
</ul>
<br><br><br>


<a href="officalfiles/Magic1.zip" class="links">Magic 1 full(532K)</a><font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The office Magic 3d programs.<br><br>
<ul type="disc"><font class="words2"></font>
	<li>The one, the only, the wounderous programs used to create and add objects to Starshatter.</li>
</ul>


</font>
</td>
</tr>
<tr><td class="sixsix" align="center" valign="bottom">
<font>
<?PHP include('scripts/executetime2.php');?>
</font>
</td></tr>
</table>
<script src="scripts/contact-copyright.js"></script>
</div>
</body>
</html>
