<html>
<HEAD>
<?PHP
include('scripts/executetime.php');
?>
<title>Starshatter Dev. - the place to find stuff you won't find anywhere else.</title>
<meta http-equiv="Content-Type" content="text/HTML; charset=iso-8859-1">
<meta name="author" content="Pheagey Grean">
<meta name="keywords" content="Starshatter, MODs, MOD, def files, meshs, 3D meshs, SS">
<meta name="description" content="A leading sourch for Stashatter MOD info.">
<meta name="reply-to" content="p_grean@hotmail.com">
<meta http-equiv="expires" content="30">

<STYLE>
IMG {behavior:url("scripts/pngbehavior.htc");}
</STYLE>
<LINK title="main" href="css/main.css" type="text/css" rel="stylesheet">
<LINK title="windef" href="css/windef.css" type="text/css" rel="alternate stylesheet">
<LINK title="aqublu" href="css/aqublu.css" type="text/css" rel="alternate stylesheet">
<!--used to change css's-->
<SCRIPT src="scripts/styleswitcher.js" type="text/javascript"></SCRIPT>
<SCRIPT language="JavaScript">
icon_image = new Image();
icon_image.src="ssd.ico";
</SCRIPT>
<LINK REL="SHORTCUT ICON" HREF="ssd.ico" >
<SCRIPT LANGUAGE=javascript src="scripts/lines.js"></SCRIPT>
</HEAD>
<body onResize="resizeBars();" onLoad="resizeBars(); setEvents(); checkOpera();"  bottommargin="0" marginheight="0" marginwidth="0" rightmargin="0" scroll="yes" topmargin="0" leftmargin="0">
<!--used to show the menu-->
<SCRIPT language=JavaScript src="scripts/menu_array.js"type="text/javascript"></SCRIPT>

<script src="scripts/titlelines.js"></script>
<script src="scripts/menu.js"></script>
<div class="bodytable">





<table width="775" align="center" cellpadding="7" cellspacing="7" border="0" bordercolor="#0000ff" >

<tr>
<td class="fourfour" rowspan="500" width="15%" align="center" valign="top">
<font class="newtitle">Magic 102</font>
</td>

<td class="sixsix" valign="top"><font class="newtitle">Magic 102- tutorial.</font></td>

<td rowspan="99" width="100" class="fourfour" height="100%" valign="top">
<script src="scripts/rightsidemenu.js"></script>
</td>
</tr>

<tr>
<td class="fourfour" ><font class="words1">
<font class="newtitle">&nbsp;&nbsp;&nbsp;Ok</font> now that you have at least a passing knowledge of the Magic interface will shall make a ship. Nothing to fancy just yet. Lets make a fighter, we'll call it F236.<br></font></td>
</tr>

<tr>
<td class="fourfour" align="left" valign="top">
<font class="words1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Open up Magic- you should be looking at this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-1.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-1.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>

nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;On the tool bar click on the 'Make Sphere' button<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-2.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-2.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Enter 6 as the number of sectors and 4 as the number of rings. If some how the 3D windows looks as if it's over top of the dialog box here's what we do: PANIC! Just kidding, it's just some kinda bug, just click where the dialog box's close button should be and close it. Then reopen the sphere dialoge box enter the data again.<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Once you have the 6 and 4 inh hit enter<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-3.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-3.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;You should now have something to the affect of this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-4.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-4.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Still with me? Good good, let continue.<BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Next we need to rotate the sphere so that the polar (top and bottom) become our bow and aft (front / back).<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;With the sphere still yellow (which means it is selected) click on the ZY window once. You will probly notice that nothing happend. thats ok all we did was pick the window we are about to use. Now goto the toolbar and click on the 'rotate button'.<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-5.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-5.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ok, go back to the ZY window click and hold the left mouse button down and move to the right untill you have rotated the sphere 90º then release. You should have this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-6.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-6.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ok, now we are going to do the same thing but on the ZX window. Click on the window, click 'rotate' and rotate 90. The ZX window shouldlook like this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-7.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-7.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now you probly notice that the sphere is not exactly lined up with the axis now. It's not of a big conseques right now but lets fix it. Click on the ZX window, then 'Drag Verts' from the toolbar. Click back on the ZX and move the sphere to the right until it's lined up.<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ok, now click the YX window and Zoom out. either by <font class="screeniewords">View-&gt; Zoom-&gt;Zoom Out</font> use the scrool wheel on your mouse if you have it. Zoom out about, mm, 200%. Now Click the '<font class="screeniewords">Scale Y</font>' buttom on the tool bar.<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-8.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-8.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Click baqck on the YX window and move the mouseup until you get something like this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-9.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-9.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now time to do some select/de-select.<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Double left click on the YX window till the sphere turns white. This means not polys / verts are selected. Next left click and hold down the button and draw a line around the aft section of the sphere. You'll see the blue line that show's what you will be selecting. Also your selection circle does not have to be perfect. MAgic will close the circle for you. So now you should have this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-10.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-10.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Go back upto the toolbar and select the '<font class="screeniewords">Scale Y</font>' button. Click on the YX window again and move the mouse DOWN until you get this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-11.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-11.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now De select everything again by double clicking anywhere but on a poly. Now select only the very aft section of the hull. Like so:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-12.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-12.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Back to the '<font class="screeniewords">Scale Y</font>' button. Now click on the YX and move youe mouse down till you getwhat this looks like:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-13.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-13.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;All right. Thats what the fighter hull will look like from the top. Next we will work on the 'side' view (ZY window).<BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Goto the ZY windows and select everything (left click and draw a circle). you should have this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-14.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-14.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Now click the '<font class="screeniewords"> Scale Z</font>' button  (on the toolbar).<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-15.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-15.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Click back on the ZY and move your mouse DOWN until the hull is about 1/2 as high as it was.<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-16.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-16.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ok, thats what hull will look like from the side. Onto the aft / bow. Click on the ZX window. You should have this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-17.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-17.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Nwo deselect everything. Now only select the very left 2 vertexes. Next select the very right 2 polygons. If done correctly you'll end up with this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-18.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-18.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ok, go back top the toolbar and hit the '<font class="screeniewords">Drag Verts</font>'.<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-19.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-19.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Head down to the ZX window, left click and move the mouse up so you end up with this:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-20.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-20.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;If everything went as planned you should now have a basic hull to a fighter that looks similar to what I have here:<BR>
<table align="center" border="2" class="sotw"><tr><td><a href="tutorials/imgs/magic102/m102-21.jpg" target="_new" BORDER="0"><IMG SRC="tutorials/imgs/magic102/tmb-m102-21.jpg" BORDER="0" align="center"></A></TD></TR></TABLE><BR><BR>
&nbsp;&nbsp;&nbsp;If you'r not happy with how yours turned out don't worry steal my copy from <a href="tutorials/files/magic102/f236.mag" target="_new" class="links">here</a>.<BR><BR>
&nbsp;&nbsp;&nbsp;Alright, DONT FORGET TO SAVE! save this in -=YouStarshatterDir=-/mods/ships/f236/f236.mag . IF the Directory mods/ships don't exist make them. There's not created with the Original install.<BR>
&nbsp;&nbsp;&nbsp;If you understood everything here and how it worked then head on over to the MAgic 3 tutorial. We're ganna make some wings, fins, and a cockpit over there.
<p align="center"><a href="magic103.php" target="_self" class="bigyellow"> =&gt; Magic 103- tutorial =&gt;</a></p><br><br><br>

<p align="right" valign="bottom"><font class="sigfont">Created: 11/3/2K2 -By: Pheagey</font></p>
</font>
</td>
</tr>
<tr><td class="sixsix" align="center" valign="bottom">
<font>
<?PHP include('scripts/executetime2.php');?>
</font>
</td></tr>
</table>
<script src="scripts/contact-copyright.js"></script>
</div>

</body>
</html>

